#### `Ali Almalki`

# 00. PyTorch Fundamentals

In [1]:
# Import required libraries 
import torch
import numpy as np

In [2]:
# Check PyTorch version 
torch.__version__

'1.11.0+cu113'

### Creating tensors 
* Scalers
* Vector
* Matrix 
* Tensor

In [3]:
# Create a Scalar (0 dimensional tensor)
scalar = torch.tensor(4)
scalar

tensor(4)

In [4]:
# Check tensor dimensions 
scalar.ndim

0

In [5]:
# Get the number within a tensor (only works with one-element tensors)
scalar.item() # Returns the value of this tensor as a standard Python number. This only works for tensors with one element.

4

In [6]:
# Create a vector (1 dimensional tesnor)
vector = torch.tensor([4, 4, 4])
vector

tensor([4, 4, 4])

In [7]:
# Check vector dimensions 
vector.ndim

1

In [8]:
# Check vector shape
vector.shape # 3 elements inside the vector

torch.Size([3])

In [9]:
# Create a matrix (2-dimensional tensor)
matrix = torch.tensor([[2, 4],
                       [3, 5]])
matrix

tensor([[2, 4],
        [3, 5]])

In [10]:
# Check matrix number of dimensions (should be 2)
matrix.ndim

2

In [11]:
# Check matrix shape 
matrix.shape

torch.Size([2, 2])

In [12]:
# Create a Tensor (n-dimensional array)
tensor = torch.tensor([[[1, 2, 7],
                        [4, 8, 9],
                        [3, 5, 7]]])
tensor

tensor([[[1, 2, 7],
         [4, 8, 9],
         [3, 5, 7]]])

In [13]:
# Check Tensor number of dimensions
tensor.ndim

3

In [14]:
# Check Tensor shape 
tensor.shape

torch.Size([1, 3, 3])

Alright, it outputs `torch.Size([1, 3, 3])`.

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Create Random Tensor

In [15]:
# Create a random tensor of size (2, 5)
random_tensor = torch.rand(size=(2, 5))
print(random_tensor)
print(f"Tensor Type: {random_tensor.dtype}")
print(f"Number of dimensions: {random_tensor.ndim}")
print(f"Tensor Shape: {random_tensor.shape}")

tensor([[0.1049, 0.7056, 0.1105, 0.0591, 0.9277],
        [0.2712, 0.1350, 0.3021, 0.0308, 0.1907]])
Tensor Type: torch.float32
Number of dimensions: 2
Tensor Shape: torch.Size([2, 5])


In [16]:
# Create another random tensor of image size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(random_image_size_tensor)
print(f"Tensor Type: {random_image_size_tensor.dtype}")
print(f"Number of dimensions: {random_image_size_tensor.ndim}")
print(f"Tensor Shape: {random_image_size_tensor.shape}")

tensor([[[0.4657, 0.9130, 0.7373],
         [0.9487, 0.1415, 0.4064],
         [0.2672, 0.3018, 0.0613],
         ...,
         [0.7560, 0.3678, 0.6883],
         [0.2372, 0.0634, 0.1817],
         [0.5049, 0.1915, 0.4595]],

        [[0.2345, 0.7512, 0.5519],
         [0.0796, 0.4815, 0.9477],
         [0.8688, 0.4204, 0.5239],
         ...,
         [0.3017, 0.9242, 0.3658],
         [0.5078, 0.6724, 0.4410],
         [0.4916, 0.4216, 0.6845]],

        [[0.0274, 0.2398, 0.6297],
         [0.9946, 0.7986, 0.8719],
         [0.8753, 0.7650, 0.9577],
         ...,
         [0.6066, 0.9361, 0.2244],
         [0.6900, 0.5473, 0.1689],
         [0.7147, 0.1547, 0.6021]],

        ...,

        [[0.6316, 0.7212, 0.5626],
         [0.5195, 0.2898, 0.6465],
         [0.0281, 0.5739, 0.2933],
         ...,
         [0.1875, 0.7263, 0.1728],
         [0.6475, 0.4682, 0.1830],
         [0.8416, 0.6335, 0.9454]],

        [[0.7613, 0.2352, 0.6157],
         [0.2156, 0.0696, 0.8664],
         [0.

### Zeros and ones

Filling tensors with zeros or ones.

This is useful for masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).


In [17]:
# Create a tensor filled with zeros
zeros = torch.zeros(size=(2, 3))
print(zeros)
print(zeros.dtype)
print(zeros.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.Size([2, 3])


In [18]:
# Create a tensor filled with ones
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype)
print(ones.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


### Creating a range and tensors like

`torch.arange(start, end, step)` 

Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

In [19]:
# Create a tensor with specific range (0, 15)
zero_to_fifteen = torch.arange(0, 15)
zero_to_fifteen, zero_to_fifteen.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 torch.Size([15]))

In [20]:
# Create a random tensor with the same shape of the previous zeros tensor
fifteen_zeros = torch.zeros_like(input=zero_to_fifteen)
fifteen_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
fifteen_ones = torch.ones_like(input=zero_to_fifteen)
fifteen_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

In [22]:
# Default tensor datatype is `float32`
float_32_tensor = torch.tensor([2.0, 3.0, 4.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
torch.float32
cpu


In [23]:
# Create a tensor with `float16` datatype
float_16_tensor = torch.tensor([5.0, 7.0, 9.0],
                               dtype=torch.float16) # torch.half would also work
print(float_16_tensor.shape)
print(float_16_tensor.dtype)
print(float_16_tensor.device)                   

torch.Size([3])
torch.float16
cpu


### Getting information from tensors

The most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

In [24]:
# Create a random tensor 
tensor = torch.rand(3, 5)

# Get tensor information 
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.2914, 0.9324, 0.9830, 0.2352, 0.9682],
        [0.7582, 0.0996, 0.4657, 0.2876, 0.9865],
        [0.1262, 0.1210, 0.3513, 0.9318, 0.3268]])
Shape of tensor: torch.Size([3, 5])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)
* addition (`+`)
* subtraction (`-`)
* mutliplication (`*`).



In [25]:
# Create a tensor 
tensor = torch.tensor([3,4,5])

# Add 20 to tensor 
tensor + 20 

tensor([23, 24, 25])

In [26]:
# Multiply it by 20
tensor * 20

tensor([ 60,  80, 100])

In [27]:
# Substract 20 from tesnor
tensor - 20

tensor([-17, -16, -15])

In [28]:
# Create two random tensors
tesnor1 = torch.rand(size=(2,3))
tensor2 = torch.rand(size=(3,2))

In [29]:
# Add 20 to tensor 1
torch.add(tesnor1, 20)

tensor([[20.0841, 20.9475, 20.9849],
        [20.3689, 20.7934, 20.9445]])

In [30]:
# Multiply 20 to tensor 1
torch.multiply(tesnor1, 20)

tensor([[ 1.6813, 18.9509, 19.6978],
        [ 7.3774, 15.8686, 18.8893]])

In [31]:
# Substract 20 from tensor 1
torch.subtract(tesnor1, 20)

tensor([[-19.9159, -19.0525, -19.0151],
        [-19.6311, -19.2066, -19.0555]])

In [32]:
# Divide 20 from tensor 1
torch.divide(tesnor1, 20)

tensor([[0.0042, 0.0474, 0.0492],
        [0.0184, 0.0397, 0.0472]])

### Matrix multiplication 

The main two rules for matrix multiplication to remember are:
1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

In [33]:
# Create a tensor 
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |

In [34]:
# Element-wise matrix multiplication 
tensor * tensor

tensor([1, 4, 9])

In [35]:
# Matrix Mutliplication
torch.matmul(tensor, tensor)
# Also tensor @ tensor works as well

tensor(14)

In [37]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [39]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [40]:
# Make inner dimensions (for matrix multiplication) match by transposing tensor_B
print(tensor_A)
print(tensor_B.T)
print(tensor_A.shape)
print(tensor_B.T.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([3, 2])
torch.Size([2, 3])


In [41]:
# Now it should work
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

I can also use [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) which is a short for `torch.matmul()`.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module, also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

In [42]:
# Make it reproducible 
torch.manual_seed(42)

# Create a linear layer (uses matrix multiplication)
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value 
linear

Linear(in_features=3, out_features=6, bias=True)

In [43]:
# Create a tensor 
x = torch.rand(size=(6, 3))
x

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]])

In [45]:
output = linear(x)
output

tensor([[-0.1424,  0.2107, -0.0216,  0.0617, -0.0686,  0.5250],
        [ 0.0799,  0.1844, -0.1334,  0.1231, -0.1050,  0.6108],
        [ 0.0667,  0.7455, -0.0570, -0.3372,  0.4239,  0.4145],
        [ 0.0403,  0.5080,  0.0963, -0.0579,  0.2659,  0.5548],
        [ 0.3437,  0.4039,  0.1604,  0.2011,  0.2371,  0.7856],
        [ 0.1363,  0.2909,  0.0383,  0.1450,  0.0626,  0.6685]],
       grad_fn=<AddmmBackward0>)

In [46]:
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([6, 3])

Output:
tensor([[-0.1424,  0.2107, -0.0216,  0.0617, -0.0686,  0.5250],
        [ 0.0799,  0.1844, -0.1334,  0.1231, -0.1050,  0.6108],
        [ 0.0667,  0.7455, -0.0570, -0.3372,  0.4239,  0.4145],
        [ 0.0403,  0.5080,  0.0963, -0.0579,  0.2659,  0.5548],
        [ 0.3437,  0.4039,  0.1604,  0.2011,  0.2371,  0.7856],
        [ 0.1363,  0.2909,  0.0383,  0.1450,  0.0626,  0.6685]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([6, 6])


### Finding the min, max, mean, sum, etc (aggregation)

In [47]:
# Create a tensor 
tensor = torch.arange(0, 50)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
tensor.dtype

torch.int64

In [49]:
# Change tensor data type 
tensor_float = tensor.to(torch.float)

In [50]:
# Find tensor max, min, mean(average) and sum

print(tensor.max())
print(tensor.min())
print(tensor_float.mean()) # Another way: print(f"Mean: {tensor.type(torch.float32).mean()}") # won't work without float datatype
print(tensor.sum())

tensor(49)
tensor(0)
tensor(24.5000)
tensor(1225)


In [51]:
# Another way with torch method 
torch.max(tensor), torch.min(tensor), torch.mean(tensor.type(torch.float32)), torch.sum(tensor)

(tensor(49), tensor(0), tensor(24.5000), tensor(1225))

### Positional min/max (Index)

In [52]:
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
# Find the index of highest and lowest value in the tensor 
tensor.argmax(), tensor.argmin()

(tensor(49), tensor(0))

### Change tensor datatype

In [54]:
# Create a tensor 
tensor = torch.arange(10, 70, 2)
tensor.dtype

torch.int64

In [55]:
# Change tensor datatype to float32
tensor_float32 = tensor.type(torch.float32)
tensor_float32

tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34., 36.,
        38., 40., 42., 44., 46., 48., 50., 52., 54., 56., 58., 60., 62., 64.,
        66., 68.])

### TENSOR VIEWS
PyTorch allows a tensor to be a View of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting View avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

In [56]:
# Create a tensor 
tensor = torch.rand(size=(2,3))
tensor

tensor([[0.7104, 0.9464, 0.7890],
        [0.2814, 0.7886, 0.5895]])

In [57]:
tensor_copy = tensor.view(1, 6) # they have to have the same size (2*3=6, 1*6=6)
tensor_copy

tensor([[0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895]])

In [58]:
# Modifying view tensor changes base tensor as well.
tensor_copy[0][0] = 3.14
tensor[0][0]

tensor(3.1400)

### Reshaping, stacking, squeezing and unsqueezing

Some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. 

In [59]:
# Create a tensor 
tensor = torch.arange(1., 8.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [60]:
# Add an extra dimension 
tensor_reshaped = tensor.reshape(1, 7)
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [61]:
# Stack tensors on top of eac[h other with stack() method
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=0)
tensor_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [62]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=1)
tensor_stacked

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])

In [63]:
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [64]:
# Remove extra dimension from tensor_reshaped (Reduce the dimensions)
tensor_squeezed = tensor_reshaped.squeeze()
tensor_squeezed, tensor_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [65]:
# Add dimension (reverse)
tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)
tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [66]:
# Create tensor with specific shape
tensor_original = torch.rand(size=(224, 224, 3))

# Permute (rearrange) the original tensor to rearrange the axis order
tensor_permuted = tensor_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {tensor_original.shape}")
print(f"New shape: {tensor_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [67]:
# Create a tensor 
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [68]:
# Let's index bracket by bracket
print(f"First square bracket:\n{tensor[0]}") 
print(f"Second square bracket: {tensor[0][0]}") 
print(f"Third square bracket: {tensor[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [69]:
tensor[:, 0], tensor[:, 1], tensor[:, 2]

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

In [70]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
tensor[:, :, 1]

tensor([[2, 5, 8]])

In [71]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
tensor[:, 1, 1]

tensor([5])

In [72]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
tensor[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

In [73]:
# Create a torch tensor from NumPy array 
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Check GPU 
!nvidia-smi

Thu Jul  7 11:26:07 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [75]:
# Test if PyTorch has access to a GPU using
torch.cuda.is_available()

True

In [76]:
# Count number of devices
torch.cuda.device_count()

1

In [77]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [82]:
# Copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)
print(tensor_on_gpu)

[1 2 3]
tensor([1, 2, 3], device='cuda:0')


### Exercises: 
1. PyTorch Documentation reading
2. Create a random tensor with shape `(7, 7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do 2 & 3 over again. The output should be:

```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape. The output should look something like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

2. Create a random tensor with shape (7, 7).

In [83]:
tensor = torch.rand(size=(7, 7))
tensor, tensor.shape

(tensor([[0.4436, 0.9726, 0.5194, 0.5337, 0.7050, 0.3362, 0.7891],
         [0.1694, 0.1800, 0.7177, 0.6988, 0.5510, 0.2485, 0.8518],
         [0.0963, 0.1338, 0.2741, 0.6142, 0.8973, 0.3629, 0.1748],
         [0.2401, 0.5457, 0.7303, 0.5268, 0.6694, 0.3213, 0.4008],
         [0.2892, 0.9977, 0.6649, 0.5646, 0.9323, 0.4621, 0.4027],
         [0.1680, 0.1170, 0.5063, 0.6061, 0.5141, 0.1907, 0.0445],
         [0.5425, 0.9580, 0.9967, 0.6417, 0.0839, 0.0765, 0.5912]]),
 torch.Size([7, 7]))

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [84]:
tensor2 = torch.rand(size=(1, 7))
tensor2

tensor([[0.8892, 0.4251, 0.8701, 0.1472, 0.6981, 0.4965, 0.0381]])

In [85]:
torch.matmul(tensor, tensor2.T)

tensor([[2.0276],
        [1.4949],
        [1.2846],
        [1.8006],
        [2.2386],
        [1.1842],
        [1.9704]])

4. Set the random seed to `0` and do 2 & 3 over again. 

In [88]:
torch.manual_seed(0)
tensor = torch.rand(size=(7, 7))
tensor2 = torch.rand(size=(1, 7))

# Matrix Multiplication 
torch.matmul(tensor, tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [96]:
torch.cuda.manual_seed(1234)


6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [99]:
# Set the seed 
torch.manual_seed(1234)

# Create random tensors
tensor1 = torch.rand(size=(2, 3))
tensor2 = torch.rand(size=(2, 3))

# Send both tensors to the GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor1_on_gpu = tensor1.to(device)
tensor2_on_gpu = tensor2.to(device)

print(tensor1_on_gpu)
print(tensor2_on_gpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [102]:
output = torch.matmul(tensor1, tensor2.T)
output

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

8. Find the maximum and minimum values of the output of 7.


In [103]:
torch.max(output), torch.min(output)

(tensor(0.5617), tensor(0.3647))

9. Find the maximum and minimum index values of the output of 7.

In [104]:
torch.argmax(output), torch.argmin(output)

(tensor(3), tensor(0))

10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape. 

In [110]:
# Set the seed 
torch.manual_seed(7)

# Create a random tensor 
random_tensor = torch.rand(size=(1, 1, 1, 10))
random_tensor

# Remove all 1 dimensions from the tensor 
random_tensor_squeezed = torch.squeeze(random_tensor)

print(random_tensor, random_tensor.shape)
print(random_tensor_squeezed, random_tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


##### Methods covered in this notebook: 

* `torch.tensor()`
* `torch.rand()`
* `torch.arange()`
* `torch.zeros()`
* `torch.ones()`
* `torch.ones_like()`
* `torch.zeros_like()`
* `torch.add()`
* `torch.subtract()`
* `torch.multiply()`
* `torch.divide()`
* `torch.matmul()` = `torch.mm()`
* `torch.manual_seed()`
* `torch.nn.Linear()`
* `torch.max()`
* `torch.min()`
* `torch.mean()`
* `torch.sum()`
* `torch.reshape()`
* `torch.squeeze()`
* `torch.unsqueeze()`
* `torch.from_numpy()`




#### **References:**

* [PyTorch Documentation](https://pytorch.org/docs/stable/index.html)

* [PyTorch Forums](https://discuss.pytorch.org/)

* [torch.Tesnor](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor)

* [Tensor Datatypes in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types)

* [Matrix Multiplication in PyTorch](https://pytorch.org/docs/stable/generated/torch.matmul.html)

* [Matrix Multiplication Explaination](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

* [Whats the difference between reshape and view in pytorch](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch/54507446#54507446)

* [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html)

* [Which GPU(s) to Get for Deep Learning](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/)

* [PyTorch Basics Tutorial](https://pytorch.org/tutorials/beginner/basics/intro.html)

* [torch.cuda()](https://pytorch.org/docs/stable/cuda.html)


* [Learn PyTorch](https://www.learnpytorch.io/00_pytorch_fundamentals/)


